# version: '3.8'
version: '2.2'
services:
  redis-server:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="gc_db"
      - MYSQL_HOST="mysqldb"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      # - PMA_HOST: "mysqldb"
      # - PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb #Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=root
      - PMA_PORT=3306
      - PMA_PASSWORD=edm2022
    restart: unless-stopped

  web:
    depends_on:
      - mysqldb
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/src
    # command: npm run start:dev
      - /src/node_modules
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    ports:
      - 3000:3000
    environment:
      - REDIS_URL="redis-server"
      - DB_HOST="mysqldb"
      - DB_USER="root"
      - DB_PASSWORD="edm2022"
      - DB_NAME="gc_db"
      - DB_PORT="3306"
      - NODE_ENV=development
      - DEBUG=portal_corporativo:*
    stdin_open: true
    tty: true
volumes: 
  db: